package ihm;

import ecouteur.EcouteurPlateau;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import moteur.Moteur;
/**
 *
 * @author disavinr
 */
public class FenetrePrincipale extends javax.swing.JFrame {

	
	 /**
     * Hauteur de la fenêtre
     */
    private static final float hauteur = (float) 2/3;
    /**
     * Largeur de la fenêtre
     */
    private static final float largeur = (float) 2/3;
    /**
     * Position X de la fenêtre
     */
    private static final float posX = (float) 1/6;
    /**
     * Position Y de la fenêtre
     */
    private static final float posY = (float) 1/6;
	
	private Moteur moteur;
	
	/** Creates new form FenetrePrincipale */
	public FenetrePrincipale(Moteur m) {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Ambition");
        moteur = m;
        //Taille et position de la fenetre
        Toolkit k = Toolkit.getDefaultToolkit();
        Dimension tailleEcran = k.getScreenSize();
        int largeurEcran = tailleEcran.width;
        int hauteurEcran = tailleEcran.height;
		initComponents();
        setSize((int) (largeurEcran*hauteur), (int) (hauteurEcran*largeur));
//        setLocation((int) (largeurEcran*posX), (int) (hauteurEcran*posY));
		setLocationRelativeTo(getParent());
		EcouteurPlateau e = new EcouteurPlateau(aireDeJeu1);
		aireDeJeu1.addMouseListener(e);
		setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aireDeJeu1 = new ihm.AireDeJeu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNouvellePartie = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout aireDeJeu1Layout = new javax.swing.GroupLayout(aireDeJeu1);
        aireDeJeu1.setLayout(aireDeJeu1Layout);
        aireDeJeu1Layout.setHorizontalGroup(
            aireDeJeu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        aireDeJeu1Layout.setVerticalGroup(
            aireDeJeu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jMenu1.setText("Fichier");

        menuNouvellePartie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNouvellePartie.setText("Nouvelle Partie");
        menuNouvellePartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNouvellePartieActionPerformed(evt);
            }
        });
        jMenu1.add(menuNouvellePartie);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Option");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aireDeJeu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aireDeJeu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void menuNouvellePartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNouvellePartieActionPerformed
		moteur.getPlateau().vider();
	}//GEN-LAST:event_menuNouvellePartieActionPerformed

	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ihm.AireDeJeu aireDeJeu1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuNouvellePartie;
    // End of variables declaration//GEN-END:variables
}
