package ihm;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import moteur.Case;
import moteur.Orientation;
import moteur.Textures;

/**
 *
 * @author Anthony
 */
public class NouvellePartiePanel extends javax.swing.JPanel {

	private AireDeJeu aire;
	/**
	 * Creates new form NewJPanel
	 */
	public NouvellePartiePanel() {
		aire = new AireDeJeu();
		
		initComponents();
//		for(Component c : j1FamillePanel1.getComponents())
//			c.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        j1Panel = new javax.swing.JPanel();
        j1NomPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        j1FamillePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        j1ClassePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        j1TextePanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        j2Panel = new javax.swing.JPanel();
        j2NomPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        j2FamillePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        j2ClassePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        j2TextePanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(64, 64, 64));
        setMinimumSize(new Dimension(Case.TAILLE * 23, Case.TAILLE * 20));
        setLayout(new java.awt.GridBagLayout());

        j1Panel.setBackground(new java.awt.Color(64, 64, 64));
        j1Panel.setPreferredSize(new Dimension(Case.TAILLE * 10, Case.TAILLE * 20));
        j1Panel.setLayout(new java.awt.GridBagLayout());

        j1NomPanel.setBackground(new java.awt.Color(128, 128, 128));
        j1NomPanel.setLayout(new java.awt.GridBagLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Entrez le nom du joueur 1 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        j1NomPanel.add(jLabel8, gridBagConstraints);

        jTextField3.setText("Joueur 1");
        jTextField3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j1NomPanel.add(jTextField3, gridBagConstraints);

        jButton18.setText("Ok");
        jButton18.setMargin(new java.awt.Insets(4, 4, 4, 4));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j1NomPanel.add(jButton18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        j1Panel.add(j1NomPanel, gridBagConstraints);

        j1FamillePanel.setBackground(new java.awt.Color(128, 128, 128));
        j1FamillePanel.setLayout(new java.awt.GridBagLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Choisissez une famille :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        j1FamillePanel.add(jLabel10, gridBagConstraints);

        jButton19.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINREPTILE, Orientation.SUD)));
        jButton19.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton19.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton19.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton19.setPreferredSize(new java.awt.Dimension(45, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j1FamillePanel.add(jButton19, gridBagConstraints);

        jButton20.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINOISEAU, Orientation.SUD)));
        jButton20.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton20.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton20.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton20.setPreferredSize(new java.awt.Dimension(45, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j1FamillePanel.add(jButton20, gridBagConstraints);

        jButton21.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINFELIN, Orientation.SUD)));
        jButton21.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton21.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton21.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton21.setPreferredSize(new java.awt.Dimension(45, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j1FamillePanel.add(jButton21, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        j1Panel.add(j1FamillePanel, gridBagConstraints);

        j1ClassePanel.setBackground(new java.awt.Color(128, 128, 128));
        j1ClassePanel.setLayout(new java.awt.GridBagLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Choisissez un pion :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        j1ClassePanel.add(jLabel11, gridBagConstraints);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton22.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton22.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton22.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton22.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j1ClassePanel.add(jButton22, gridBagConstraints);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton23.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton23.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton23.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton23.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j1ClassePanel.add(jButton23, gridBagConstraints);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton28.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton28.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton28.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton28.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j1ClassePanel.add(jButton28, gridBagConstraints);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton29.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton29.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton29.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton29.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j1ClassePanel.add(jButton29, gridBagConstraints);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton30.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton30.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton30.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton30.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j1ClassePanel.add(jButton30, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 0);
        j1Panel.add(j1ClassePanel, gridBagConstraints);

        j1TextePanel.setBackground(new java.awt.Color(128, 128, 128));

        jTextArea4.setBackground(new java.awt.Color(128, 128, 128));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setEnabled(false);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout j1TextePanelLayout = new javax.swing.GroupLayout(j1TextePanel);
        j1TextePanel.setLayout(j1TextePanelLayout);
        j1TextePanelLayout.setHorizontalGroup(
            j1TextePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );
        j1TextePanelLayout.setVerticalGroup(
            j1TextePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 2.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        j1Panel.add(j1TextePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(j1Panel, gridBagConstraints);

        j2Panel.setBackground(new java.awt.Color(64, 64, 64));
        j2Panel.setPreferredSize(new Dimension(Case.TAILLE * 10, Case.TAILLE * 20));
        j2Panel.setLayout(new java.awt.GridBagLayout());

        j2NomPanel.setBackground(new java.awt.Color(128, 128, 128));
        j2NomPanel.setLayout(new java.awt.GridBagLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Entrez le nom du joueur 2 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        j2NomPanel.add(jLabel6, gridBagConstraints);

        jTextField4.setText("Joueur 2");
        jTextField4.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j2NomPanel.add(jTextField4, gridBagConstraints);

        jButton10.setText("Ok");
        jButton10.setMargin(new java.awt.Insets(4, 4, 4, 4));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j2NomPanel.add(jButton10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        j2Panel.add(j2NomPanel, gridBagConstraints);

        j2FamillePanel.setBackground(new java.awt.Color(128, 128, 128));
        j2FamillePanel.setLayout(new java.awt.GridBagLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Choisissez une famille :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        j2FamillePanel.add(jLabel7, gridBagConstraints);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/obstacle/eau/eau.png"))); // NOI18N
        jButton11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton11.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton11.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton11.setPreferredSize(new java.awt.Dimension(45, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j2FamillePanel.add(jButton11, gridBagConstraints);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/herbemod.png"))); // NOI18N
        jButton12.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton12.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton12.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton12.setPreferredSize(new java.awt.Dimension(45, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j2FamillePanel.add(jButton12, gridBagConstraints);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/sable.png"))); // NOI18N
        jButton13.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton13.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton13.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton13.setPreferredSize(new java.awt.Dimension(45, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        j2FamillePanel.add(jButton13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        j2Panel.add(j2FamillePanel, gridBagConstraints);

        j2ClassePanel.setBackground(new java.awt.Color(128, 128, 128));
        j2ClassePanel.setLayout(new java.awt.GridBagLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Choisissez un pion :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        j2ClassePanel.add(jLabel13, gridBagConstraints);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton16.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton16.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton16.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton16.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j2ClassePanel.add(jButton16, gridBagConstraints);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton17.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton17.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton17.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton17.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j2ClassePanel.add(jButton17, gridBagConstraints);

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton37.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton37.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton37.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton37.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j2ClassePanel.add(jButton37, gridBagConstraints);

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton38.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton38.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton38.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton38.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j2ClassePanel.add(jButton38, gridBagConstraints);

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/texture/glace.png"))); // NOI18N
        jButton39.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton39.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton39.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton39.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 5);
        j2ClassePanel.add(jButton39, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 0);
        j2Panel.add(j2ClassePanel, gridBagConstraints);

        j2TextePanel.setBackground(new java.awt.Color(128, 128, 128));

        jTextArea5.setBackground(new java.awt.Color(128, 128, 128));
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setEnabled(false);
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout j2TextePanelLayout = new javax.swing.GroupLayout(j2TextePanel);
        j2TextePanel.setLayout(j2TextePanelLayout);
        j2TextePanelLayout.setHorizontalGroup(
            j2TextePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
        j2TextePanelLayout.setVerticalGroup(
            j2TextePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 2.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        j2Panel.add(j2TextePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(j2Panel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel j1ClassePanel;
    private javax.swing.JPanel j1FamillePanel;
    private javax.swing.JPanel j1NomPanel;
    private javax.swing.JPanel j1Panel;
    private javax.swing.JPanel j1TextePanel;
    private javax.swing.JPanel j2ClassePanel;
    private javax.swing.JPanel j2FamillePanel;
    private javax.swing.JPanel j2NomPanel;
    private javax.swing.JPanel j2Panel;
    private javax.swing.JPanel j2TextePanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
