package ihm;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import moteur.Joueur;
import moteur.Orientation;
import moteur.Textures;
import moteur.classes.Tacticien;
import moteur.familles.felin.ArcherFelin;
import moteur.familles.felin.TacticienFelin;
import moteur.familles.oiseau.ArcherOiseau;
import moteur.familles.oiseau.TacticienOiseau;
import moteur.familles.reptile.ArcherReptile;
import moteur.familles.reptile.TacticienReptile;

/**
 *
 * @author Kévin
 */
public class NouvellePartie extends javax.swing.JDialog {
	private FenetrePrincipale parent;
	private final int NBPION = 16;
	private int choix = 0;
	private final int REPTILE = 0;
	private final int OISEAU = 1;
	private final int FELIN = 2;
	private int famille1;
	private int famille2;
	/**
	 * Creates new form NouvellePartie
	 */
	public NouvellePartie(FenetrePrincipale parent, boolean modal) {
		super(parent, modal);
		this.parent = parent;
		initComponents();
		setLocationRelativeTo(getParent());
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pseudo2 = new javax.swing.JTextField();
        Reptile2 = new javax.swing.JButton();
        Oiseau2 = new javax.swing.JButton();
        Felin2 = new javax.swing.JButton();
        Archer2 = new javax.swing.JButton();
        Tank2 = new javax.swing.JButton();
        Assassin2 = new javax.swing.JButton();
        Guerrier2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        j2p12 = new javax.swing.JLabel();
        j2p13 = new javax.swing.JLabel();
        j2p14 = new javax.swing.JLabel();
        j2p5 = new javax.swing.JLabel();
        j2p9 = new javax.swing.JLabel();
        j2p3 = new javax.swing.JLabel();
        j2p4 = new javax.swing.JLabel();
        j2p10 = new javax.swing.JLabel();
        j2p11 = new javax.swing.JLabel();
        j2p16 = new javax.swing.JLabel();
        j2p15 = new javax.swing.JLabel();
        j2p1 = new javax.swing.JLabel();
        j2p6 = new javax.swing.JLabel();
        j2p7 = new javax.swing.JLabel();
        j2p8 = new javax.swing.JLabel();
        j2p2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reptile1 = new javax.swing.JButton();
        Archer1 = new javax.swing.JButton();
        Assassin1 = new javax.swing.JButton();
        Oiseau1 = new javax.swing.JButton();
        Felin1 = new javax.swing.JButton();
        pseudo1 = new javax.swing.JTextField();
        Guerrier1 = new javax.swing.JButton();
        Tank1 = new javax.swing.JButton();
        joueurLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        j1p11 = new javax.swing.JLabel();
        j1p12 = new javax.swing.JLabel();
        j1p9 = new javax.swing.JLabel();
        j1p10 = new javax.swing.JLabel();
        j1p15 = new javax.swing.JLabel();
        j1p13 = new javax.swing.JLabel();
        j1p14 = new javax.swing.JLabel();
        j1p16 = new javax.swing.JLabel();
        j1p1 = new javax.swing.JLabel();
        j1p2 = new javax.swing.JLabel();
        j1p3 = new javax.swing.JLabel();
        j1p4 = new javax.swing.JLabel();
        j1p5 = new javax.swing.JLabel();
        j1p6 = new javax.swing.JLabel();
        j1p8 = new javax.swing.JLabel();
        j1p7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouvelle Partie");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nouvelle partie");

        jLabel2.setText("Joueur 2");

        jLabel4.setText("Nom :");

        pseudo2.setText("joueur_2");

        Reptile2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINREPTILE, Orientation.SUD)));
        Reptile2.setToolTipText("Reptile : vie (+3), force (+2), vitesse (-2)");
        Reptile2.setBorderPainted(false);
        Reptile2.setEnabled(false);
        Reptile2.setMaximumSize(new java.awt.Dimension(32, 32));
        Reptile2.setMinimumSize(new java.awt.Dimension(32, 32));
        Reptile2.setPreferredSize(new java.awt.Dimension(32, 32));
        Reptile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reptile2ActionPerformed(evt);
            }
        });

        Oiseau2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINOISEAU, Orientation.SUD)));
        Oiseau2.setToolTipText("Oiseau : précision (+3), vitesse (+2), défense (-2)");
        Oiseau2.setBorderPainted(false);
        Oiseau2.setEnabled(false);
        Oiseau2.setMaximumSize(new java.awt.Dimension(32, 32));
        Oiseau2.setMinimumSize(new java.awt.Dimension(32, 32));
        Oiseau2.setPreferredSize(new java.awt.Dimension(32, 32));
        Oiseau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oiseau2ActionPerformed(evt);
            }
        });

        Felin2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINFELIN, Orientation.SUD)));
        Felin2.setToolTipText("Félin : défense (+3), chance (+2), vie (-2)");
        Felin2.setBorderPainted(false);
        Felin2.setEnabled(false);
        Felin2.setMaximumSize(new java.awt.Dimension(32, 32));
        Felin2.setMinimumSize(new java.awt.Dimension(32, 32));
        Felin2.setPreferredSize(new java.awt.Dimension(32, 32));
        Felin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Felin2ActionPerformed(evt);
            }
        });

        Archer2.setEnabled(false);
        Archer2.setMaximumSize(new java.awt.Dimension(32, 32));
        Archer2.setMinimumSize(new java.awt.Dimension(32, 32));
        Archer2.setPreferredSize(new java.awt.Dimension(32, 32));
        Archer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Archer2ActionPerformed(evt);
            }
        });

        Tank2.setEnabled(false);
        Tank2.setMaximumSize(new java.awt.Dimension(32, 32));
        Tank2.setMinimumSize(new java.awt.Dimension(32, 32));
        Tank2.setPreferredSize(new java.awt.Dimension(32, 32));
        Tank2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tank2ActionPerformed(evt);
            }
        });

        Assassin2.setEnabled(false);
        Assassin2.setMaximumSize(new java.awt.Dimension(32, 32));
        Assassin2.setMinimumSize(new java.awt.Dimension(32, 32));
        Assassin2.setPreferredSize(new java.awt.Dimension(32, 32));
        Assassin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assassin2ActionPerformed(evt);
            }
        });

        Guerrier2.setEnabled(false);
        Guerrier2.setMaximumSize(new java.awt.Dimension(32, 32));
        Guerrier2.setMinimumSize(new java.awt.Dimension(32, 32));
        Guerrier2.setPreferredSize(new java.awt.Dimension(32, 32));
        Guerrier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guerrier2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(pseudo2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Reptile2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Oiseau2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Felin2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Archer2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Assassin2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Guerrier2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tank2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pseudo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Felin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Reptile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Archer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Assassin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Guerrier2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Oiseau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        j2p12.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p13.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p14.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p5.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p9.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p3.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p4.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p10.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p11.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p16.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p15.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p1.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p6.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p7.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p8.setPreferredSize(new java.awt.Dimension(32, 32));

        j2p2.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(j2p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(j2p13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(j2p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(j2p9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j2p12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2p9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2p13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2p16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Nom :");

        reptile1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINREPTILE, Orientation.SUD)));
        reptile1.setToolTipText("Reptile : vie (+3), force (+2), vitesse (-2)");
        reptile1.setBorderPainted(false);
        reptile1.setMaximumSize(new java.awt.Dimension(32, 32));
        reptile1.setMinimumSize(new java.awt.Dimension(32, 32));
        reptile1.setPreferredSize(new java.awt.Dimension(32, 32));
        reptile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reptile1ActionPerformed(evt);
            }
        });

        Archer1.setEnabled(false);
        Archer1.setMaximumSize(new java.awt.Dimension(32, 32));
        Archer1.setMinimumSize(new java.awt.Dimension(32, 32));
        Archer1.setPreferredSize(new java.awt.Dimension(32, 32));
        Archer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Archer1ActionPerformed(evt);
            }
        });

        Assassin1.setEnabled(false);
        Assassin1.setMaximumSize(new java.awt.Dimension(32, 32));
        Assassin1.setMinimumSize(new java.awt.Dimension(32, 32));
        Assassin1.setPreferredSize(new java.awt.Dimension(32, 32));
        Assassin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assassin1ActionPerformed(evt);
            }
        });

        Oiseau1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINOISEAU, Orientation.SUD)));
        Oiseau1.setToolTipText("Oiseau : précision (+3), vitesse (+2), défense (-2)");
        Oiseau1.setBorderPainted(false);
        Oiseau1.setMaximumSize(new java.awt.Dimension(32, 32));
        Oiseau1.setMinimumSize(new java.awt.Dimension(32, 32));
        Oiseau1.setPreferredSize(new java.awt.Dimension(32, 32));
        Oiseau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oiseau1ActionPerformed(evt);
            }
        });

        Felin1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINFELIN, Orientation.SUD)));
        Felin1.setToolTipText("Félin : défense (+3), chance (+2), vie (-2)");
        Felin1.setBorderPainted(false);
        Felin1.setMaximumSize(new java.awt.Dimension(32, 32));
        Felin1.setMinimumSize(new java.awt.Dimension(32, 32));
        Felin1.setPreferredSize(new java.awt.Dimension(32, 32));
        Felin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Felin1ActionPerformed(evt);
            }
        });

        pseudo1.setText("joueur_1");

        Guerrier1.setEnabled(false);
        Guerrier1.setMaximumSize(new java.awt.Dimension(32, 32));
        Guerrier1.setMinimumSize(new java.awt.Dimension(32, 32));
        Guerrier1.setPreferredSize(new java.awt.Dimension(32, 32));
        Guerrier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guerrier1ActionPerformed(evt);
            }
        });

        Tank1.setEnabled(false);
        Tank1.setMaximumSize(new java.awt.Dimension(32, 32));
        Tank1.setMinimumSize(new java.awt.Dimension(32, 32));
        Tank1.setPreferredSize(new java.awt.Dimension(32, 32));
        Tank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tank1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reptile1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Oiseau1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Felin1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pseudo1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Archer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Assassin1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Guerrier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tank1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pseudo1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reptile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Oiseau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Felin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Archer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Assassin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guerrier1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tank1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        joueurLabel.setText("Joueur 1");

        j1p11.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p12.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p9.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p10.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p15.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p13.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p14.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p16.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p1.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p2.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p3.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p4.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p5.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p6.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p8.setPreferredSize(new java.awt.Dimension(32, 32));

        j1p7.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(j1p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(j1p13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(j1p9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(j1p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(j1p8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1p9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1p13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1p16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(joueurLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(540, 540, 540))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(joueurLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void reptile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reptile1ActionPerformed
		reptile1.setEnabled(false);
		Oiseau1.setEnabled(false);
		Felin1.setEnabled(false);
		Archer1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ARCHERREPTILE, Orientation.SUD)));
		Assassin1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINREPTILE, Orientation.SUD)));
		Guerrier1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.GUERRIERREPTILE, Orientation.SUD)));
		Tank1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TANKREPTILE, Orientation.SUD)));
		Reptile2.setEnabled(true);
		Oiseau2.setEnabled(true);
		Felin2.setEnabled(true);
		famille1 = REPTILE;
		parent.getMoteur().getJoueur1().ajouterPion(new TacticienReptile(null));
		j1p1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TACTICIENREPTILE, Orientation.SUD)));
	}//GEN-LAST:event_reptile1ActionPerformed

	private void Oiseau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oiseau1ActionPerformed
		reptile1.setEnabled(false);
		Oiseau1.setEnabled(false);
		Felin1.setEnabled(false);
		Archer1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ARCHEROISEAU, Orientation.SUD)));
		Assassin1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINOISEAU, Orientation.SUD)));
		Guerrier1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.GUERRIEROISEAU, Orientation.SUD)));
		Tank1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TANKOISEAU, Orientation.SUD)));
		Reptile2.setEnabled(true);
		Oiseau2.setEnabled(true);
		Felin2.setEnabled(true);
		famille1 = OISEAU;
		parent.getMoteur().getJoueur1().ajouterPion(new TacticienOiseau(null));		
		j1p1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TACTICIENOISEAU, Orientation.SUD)));
	}//GEN-LAST:event_Oiseau1ActionPerformed

	private void Felin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Felin1ActionPerformed
		reptile1.setEnabled(false);
		Oiseau1.setEnabled(false);
		Felin1.setEnabled(false);
		Archer1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ARCHERFELIN, Orientation.SUD)));
		Assassin1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINFELIN, Orientation.SUD)));
		Guerrier1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.GUERRIERFELIN, Orientation.SUD)));
		Tank1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TANKFELIN, Orientation.SUD)));
		Reptile2.setEnabled(true);
		Oiseau2.setEnabled(true);
		Felin2.setEnabled(true);
		famille1 = FELIN;
		parent.getMoteur().getJoueur1().ajouterPion(new TacticienFelin(null));
		j1p1.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TACTICIENFELIN, Orientation.SUD)));
	}//GEN-LAST:event_Felin1ActionPerformed

	private void Reptile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reptile2ActionPerformed
		Reptile2.setEnabled(false);
		Oiseau2.setEnabled(false);
		Felin2.setEnabled(false);
		Archer2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ARCHERREPTILE, Orientation.SUD)));
		Assassin2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINREPTILE, Orientation.SUD)));
		Guerrier2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.GUERRIERREPTILE, Orientation.SUD)));
		Tank2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TANKREPTILE, Orientation.SUD)));
		Archer1.setEnabled(true);
		Assassin1.setEnabled(true);
		Tank1.setEnabled(true);
		Guerrier1.setEnabled(true);
		famille2 = REPTILE;
		parent.getMoteur().getJoueur2().ajouterPion(new TacticienReptile(null));
	}//GEN-LAST:event_Reptile2ActionPerformed

	private void Oiseau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oiseau2ActionPerformed
		Reptile2.setEnabled(false);
		Oiseau2.setEnabled(false);
		Felin2.setEnabled(false);
		Archer2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ARCHEROISEAU, Orientation.SUD)));
		Assassin2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINOISEAU, Orientation.SUD)));
		Guerrier2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.GUERRIEROISEAU, Orientation.SUD)));
		Tank2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TANKOISEAU, Orientation.SUD)));
		Archer1.setEnabled(true);
		Assassin1.setEnabled(true);
		Tank1.setEnabled(true);
		Guerrier1.setEnabled(true);
		famille2 = OISEAU;
		parent.getMoteur().getJoueur2().ajouterPion(new TacticienOiseau(null));
	}//GEN-LAST:event_Oiseau2ActionPerformed

	private void Felin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Felin2ActionPerformed
		Reptile2.setEnabled(false);
		Oiseau2.setEnabled(false);
		Felin2.setEnabled(false);
		Archer2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ARCHERFELIN, Orientation.SUD)));
		Assassin2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.ASSASSINFELIN, Orientation.SUD)));
		Guerrier2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.GUERRIERFELIN, Orientation.SUD)));
		Tank2.setIcon(new ImageIcon(Textures.getPersonnage(Textures.TANKFELIN, Orientation.SUD)));
		Archer1.setEnabled(true);
		Assassin1.setEnabled(true);
		Tank1.setEnabled(true);
		Guerrier1.setEnabled(true);
		famille2 = FELIN;
		parent.getMoteur().getJoueur2().ajouterPion(new TacticienFelin(null));
	}//GEN-LAST:event_Felin2ActionPerformed

	private void Archer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Archer1ActionPerformed
		switch(famille1){
			case REPTILE:
				parent.getMoteur().getJoueur1().ajouterPion(new ArcherReptile(null));
				break;
			case OISEAU:
				parent.getMoteur().getJoueur1().ajouterPion(new ArcherOiseau(null));
				break;
			case FELIN:
				parent.getMoteur().getJoueur1().ajouterPion(new ArcherFelin(null));
		}
		
	}//GEN-LAST:event_Archer1ActionPerformed

	private void Assassin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assassin1ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_Assassin1ActionPerformed

	private void Guerrier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guerrier1ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_Guerrier1ActionPerformed

	private void Tank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tank1ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_Tank1ActionPerformed

	private void Archer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Archer2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_Archer2ActionPerformed

	private void Assassin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assassin2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_Assassin2ActionPerformed

	private void Guerrier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guerrier2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_Guerrier2ActionPerformed

	private void Tank2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tank2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_Tank2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Archer1;
    private javax.swing.JButton Archer2;
    private javax.swing.JButton Assassin1;
    private javax.swing.JButton Assassin2;
    private javax.swing.JButton Felin1;
    private javax.swing.JButton Felin2;
    private javax.swing.JButton Guerrier1;
    private javax.swing.JButton Guerrier2;
    private javax.swing.JButton Oiseau1;
    private javax.swing.JButton Oiseau2;
    private javax.swing.JButton Reptile2;
    private javax.swing.JButton Tank1;
    private javax.swing.JButton Tank2;
    private javax.swing.JLabel j1p1;
    private javax.swing.JLabel j1p10;
    private javax.swing.JLabel j1p11;
    private javax.swing.JLabel j1p12;
    private javax.swing.JLabel j1p13;
    private javax.swing.JLabel j1p14;
    private javax.swing.JLabel j1p15;
    private javax.swing.JLabel j1p16;
    private javax.swing.JLabel j1p2;
    private javax.swing.JLabel j1p3;
    private javax.swing.JLabel j1p4;
    private javax.swing.JLabel j1p5;
    private javax.swing.JLabel j1p6;
    private javax.swing.JLabel j1p7;
    private javax.swing.JLabel j1p8;
    private javax.swing.JLabel j1p9;
    private javax.swing.JLabel j2p1;
    private javax.swing.JLabel j2p10;
    private javax.swing.JLabel j2p11;
    private javax.swing.JLabel j2p12;
    private javax.swing.JLabel j2p13;
    private javax.swing.JLabel j2p14;
    private javax.swing.JLabel j2p15;
    private javax.swing.JLabel j2p16;
    private javax.swing.JLabel j2p2;
    private javax.swing.JLabel j2p3;
    private javax.swing.JLabel j2p4;
    private javax.swing.JLabel j2p5;
    private javax.swing.JLabel j2p6;
    private javax.swing.JLabel j2p7;
    private javax.swing.JLabel j2p8;
    private javax.swing.JLabel j2p9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel joueurLabel;
    private javax.swing.JTextField pseudo1;
    private javax.swing.JTextField pseudo2;
    private javax.swing.JButton reptile1;
    // End of variables declaration//GEN-END:variables
}
