/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChoixTexture.java
 *
 * Created on 15 nov. 2012, 16:36:13
 */
package editeur;

import moteur.Case;
import moteur.Textures;

/**
 *
 * @author disavinr
 */
public class ChoixTexture extends javax.swing.JDialog {

    private FenetreEditeur fe;
    private Case c1;
    private Case c2;

    /**
     * Creates new form ChoixTexture
     */
    public ChoixTexture(FenetreEditeur parent, Case c1, Case c2) {
	super(parent, true);
	fe = parent;
	this.c1 = c1;
	this.c2 = c2;
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Roc");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Eau");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Sable");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Herbe");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Route");

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(annulerButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(annulerButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
	    int texture;
	    if (jRadioButton1.isSelected()) {
		texture = Textures.ROC;
	    } else if (jRadioButton2.isSelected()) {
		texture = Textures.EAU;
	    } else if (jRadioButton3.isSelected()) {
		texture = Textures.SABLE;
	    } else if (jRadioButton4.isSelected()) {
		texture = Textures.HERBE;
	    } else {
		texture = Textures.ROUTE;
	    }
	    int ligneMin = Math.min(c1.getLigne(), c2.getLigne());
	    int ligneMax = Math.max(c1.getLigne(), c2.getLigne());
	    int colonneMin = Math.min(c1.getColonne(), c2.getColonne());
	    int colonneMax = Math.max(c1.getColonne(), c2.getColonne());
	    
	    Case[][] c = fe.getAireDeJeu1().getPlateau().get();
	    for (int i = ligneMin; i <= ligneMax; i++) {
		for (int j = colonneMin; j <= colonneMax; j++) {
		    c[i][j].setTypeTerrain(texture);
		}
	    }
	    fe.getAireDeJeu1().repaint();
	    dispose();
	}//GEN-LAST:event_okButtonActionPerformed

	private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
	    dispose();
	}//GEN-LAST:event_annulerButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
