package editeur;

import ecouteur.EcouteurEditeur;
import ihm.AireDeJeu;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import moteur.Plateau;
import moteur.Textures;

/**
 *
 * @author disavinr
 */
public class FenetreEditeur extends javax.swing.JFrame {

    private Editeur editeur;
    public int texture;
    public boolean obstacle;
    public boolean suppression;
    public boolean bordure;
    EcouteurEditeur ecouteur;

    /**
     * Creates new form FenetreEditeur
     */
    public FenetreEditeur(Editeur e) {
	editeur = e;
	ecouteur = new EcouteurEditeur(this);
	initComponents();
	setLocationRelativeTo(getParent());

	aireDeJeu1.addMouseListener(ecouteur);
	aireDeJeu1.addMouseMotionListener(ecouteur);

	setVisible(true);
	obstacle = false;
	suppression = false;
	bordure = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        aireDeJeu1 = new ihm.AireDeJeu(editeur.getPlateau());
        aireDeSelection1 = new editeur.AireDeSelection(ecouteur);
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        creerMap = new javax.swing.JMenuItem();
        chargerMap = new javax.swing.JMenuItem();
        sauverMap = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editeur de carte");

        javax.swing.GroupLayout aireDeSelection1Layout = new javax.swing.GroupLayout(aireDeSelection1);
        aireDeSelection1.setLayout(aireDeSelection1Layout);
        aireDeSelection1Layout.setHorizontalGroup(
            aireDeSelection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        aireDeSelection1Layout.setVerticalGroup(
            aireDeSelection1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout aireDeJeu1Layout = new javax.swing.GroupLayout(aireDeJeu1);
        aireDeJeu1.setLayout(aireDeJeu1Layout);
        aireDeJeu1Layout.setHorizontalGroup(
            aireDeJeu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aireDeSelection1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        aireDeJeu1Layout.setVerticalGroup(
            aireDeJeu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aireDeSelection1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setBorderPainted(true);
        jRadioButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/herbe.png"))); // NOI18N
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setBorderPainted(true);
        jRadioButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauFondBas.png"))); // NOI18N
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setBorderPainted(true);
        jRadioButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureEauBas.png"))); // NOI18N
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setBorderPainted(true);
        jRadioButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauDroit.png"))); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setBorderPainted(true);
        jRadioButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauGauche.png"))); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setBorderPainted(true);
        jRadioButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauHaut.png"))); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setBorderPainted(true);
        jRadioButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauHautGauche.png"))); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setBorderPainted(true);
        jRadioButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureEauDroit.png"))); // NOI18N
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setBorderPainted(true);
        jRadioButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureEauGauche.png"))); // NOI18N
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setBorderPainted(true);
        jRadioButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauFondDroit.png"))); // NOI18N
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setBorderPainted(true);
        jRadioButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauVirageBasDroit.png"))); // NOI18N
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setBorderPainted(true);
        jRadioButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauVirageHautDroit.png"))); // NOI18N
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setBorderPainted(true);
        jRadioButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauFondGauche.png"))); // NOI18N
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setBorderPainted(true);
        jRadioButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauVirageHautGauche.png"))); // NOI18N
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setBorderPainted(true);
        jRadioButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauVirageBasGauche.png"))); // NOI18N
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setBorderPainted(true);
        jRadioButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eau.png"))); // NOI18N
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton17);
        jRadioButton17.setBorderPainted(true);
        jRadioButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eauHautDroit.png"))); // NOI18N
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setBorderPainted(true);
        jRadioButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneHautGauche.png"))); // NOI18N
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setBorderPainted(true);
        jRadioButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneBas.png"))); // NOI18N
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton20);
        jRadioButton20.setBorderPainted(true);
        jRadioButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneCentre.png"))); // NOI18N
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setBorderPainted(true);
        jRadioButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneCentreGauche.png"))); // NOI18N
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.setBorderPainted(true);
        jRadioButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneBasGauche.png"))); // NOI18N
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton23);
        jRadioButton23.setBorderPainted(true);
        jRadioButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneHaut.png"))); // NOI18N
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton24);
        jRadioButton24.setBorderPainted(true);
        jRadioButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneHautDroite.png"))); // NOI18N
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton25);
        jRadioButton25.setBorderPainted(true);
        jRadioButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneCentreDroit.png"))); // NOI18N
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton26);
        jRadioButton26.setBorderPainted(true);
        jRadioButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montagneBasDroit.png"))); // NOI18N
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton27);
        jRadioButton27.setText("Supprimer obstacle || bordure");
        jRadioButton27.setBorderPainted(true);
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton32);
        jRadioButton32.setBorderPainted(true);
        jRadioButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sableCentre.png"))); // NOI18N
        jRadioButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton32ActionPerformed(evt);
            }
        });

        jLabel1.setText("OBSTACLE INDESTRCUTIBLE");

        jLabel2.setText(" - Eau");

        jLabel3.setText(" - Montagne");

        jLabel4.setText("TERRAIN");

        jLabel5.setText("Sable");

        jLabel6.setText("Bordure");

        jLabel7.setText("Bordure");

        buttonGroup1.add(jRadioButton28);
        jRadioButton28.setBorderPainted(true);
        jRadioButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableHautGauche.png"))); // NOI18N
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton29);
        jRadioButton29.setBorderPainted(true);
        jRadioButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableHaut.png"))); // NOI18N
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton30);
        jRadioButton30.setBorderPainted(true);
        jRadioButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableHautDroit.png"))); // NOI18N
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton31);
        jRadioButton31.setBorderPainted(true);
        jRadioButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableGauche.png"))); // NOI18N
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton33);
        jRadioButton33.setBorderPainted(true);
        jRadioButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableDroit.png"))); // NOI18N
        jRadioButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton33ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton34);
        jRadioButton34.setBorderPainted(true);
        jRadioButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableBasGauche.png"))); // NOI18N
        jRadioButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton34ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton35);
        jRadioButton35.setBorderPainted(true);
        jRadioButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableBas.png"))); // NOI18N
        jRadioButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton35ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton36);
        jRadioButton36.setBorderPainted(true);
        jRadioButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableBasDroit.png"))); // NOI18N
        jRadioButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton36ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton37);
        jRadioButton37.setBorderPainted(true);
        jRadioButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bordureSableCoinBasDroit.png"))); // NOI18N
        jRadioButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton37ActionPerformed(evt);
            }
        });

        jMenu1.setText("Fichier");

        creerMap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        creerMap.setText("Créer carte");
        creerMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerMapActionPerformed(evt);
            }
        });
        jMenu1.add(creerMap);

        chargerMap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        chargerMap.setText("Charger carte");
        chargerMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargerMapActionPerformed(evt);
            }
        });
        jMenu1.add(chargerMap);

        sauverMap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        sauverMap.setText("Enregistrer carte");
        sauverMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauverMapActionPerformed(evt);
            }
        });
        jMenu1.add(sauverMap);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButton5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton37)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aireDeJeu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton27)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton16))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jRadioButton18)
                                                    .addComponent(jRadioButton21)
                                                    .addComponent(jRadioButton22))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jRadioButton20)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jRadioButton25))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jRadioButton23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jRadioButton24))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jRadioButton19)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jRadioButton26)))))
                                        .addGap(63, 63, 63)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton8))
                                            .addComponent(jRadioButton7))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton17)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton12)
                                    .addComponent(jRadioButton14)
                                    .addComponent(jRadioButton11)
                                    .addComponent(jRadioButton15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton16)
                                    .addComponent(jRadioButton13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton6)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton18)
                                            .addComponent(jRadioButton23)
                                            .addComponent(jRadioButton24))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton25)
                                            .addComponent(jRadioButton20)
                                            .addComponent(jRadioButton21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton19)
                                            .addComponent(jRadioButton26)
                                            .addComponent(jRadioButton22)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton7))
                            .addComponent(jRadioButton8))
                        .addGap(260, 260, 260))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aireDeJeu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton28)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5))
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton31)
                    .addComponent(jRadioButton33)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton36)
                    .addComponent(jRadioButton37))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public AireDeSelection getAire() {
	return aireDeSelection1;
    }
    private void sauverMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauverMapActionPerformed
	JFileChooser fc = new JFileChooser();
	if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
	    File fichier = fc.getSelectedFile();

	    FileOutputStream fos = null;
	    try {
		fos = new FileOutputStream(fichier);
	    } catch (FileNotFoundException ex) {
		Logger.getLogger(FenetreEditeur.class.getName()).log(Level.SEVERE, null, ex);
	    }

	    if (fos != null) {
		ObjectOutputStream oos = null;
		try {
		    oos = new ObjectOutputStream(fos);
		} catch (IOException ex) {
		    Logger.getLogger(FenetreEditeur.class.getName()).log(Level.SEVERE, null, ex);
		} finally {
		    try {
			oos.writeObject(aireDeJeu1.getPlateau());
			oos.close();
			fos.close();
		    } catch (IOException ex) {
			Logger.getLogger(FenetreEditeur.class.getName()).log(Level.SEVERE, null, ex);
		    }
		}
	    }
	}
    }//GEN-LAST:event_sauverMapActionPerformed

    private void chargerMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargerMapActionPerformed
	JFileChooser fc = new JFileChooser();
	System.out.println(aireDeJeu1.getPlateau());
	if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
	    File fichier = fc.getSelectedFile();

	    if (fichier.exists()) {
		FileInputStream fis = null;
		try {
		    fis = new FileInputStream(fichier);
		} catch (FileNotFoundException ex) {
		    Logger.getLogger(FenetreEditeur.class.getName()).log(Level.SEVERE, null, ex);
		}

		if (fis != null) {
		    ObjectInputStream ois = null;
		    try {
			ois = new ObjectInputStream(fis);
		    } catch (IOException ex) {
			Logger.getLogger(FenetreEditeur.class.getName()).log(Level.SEVERE, null, ex);
		    } finally {
			try {
			    Plateau p = (Plateau) ois.readObject();
			    for (int i = 0; i < aireDeJeu1.getPlateau().getNbLigne(); i++) {
				for (int j = 0; j < aireDeJeu1.getPlateau().getNbColonne(); j++) {
				    aireDeJeu1.getPlateau().get(i, j).setBordure(p.get(i, j).getBordure());
				    aireDeJeu1.getPlateau().get(i, j).setObstacle(p.get(i, j).getObstacle());
				    aireDeJeu1.getPlateau().get(i, j).setTypeTerrain(p.get(i, j).getTypeTerrain());
				}
			    }
			    aireDeJeu1.repaint();
			    ois.close();
			    fis.close();
			} catch (IOException ex) {
			    Logger.getLogger(FenetreEditeur.class.getName()).log(Level.SEVERE, null, ex);
			} catch (ClassNotFoundException ex) {
			    Logger.getLogger(Plateau.class.getName()).log(Level.SEVERE, null, ex);
			}
		    }
		}
	    } else {
		System.err.println("Le fichier n'existe pas");
	    }
	    for (int i = 0; i < aireDeJeu1.getPlateau().getNbLigne(); i++) {
		for (int j = 0; j < aireDeJeu1.getPlateau().getNbColonne(); j++) {
		    System.out.print(aireDeJeu1.getPlateau().get(i, j).getTypeTerrain());
		}
		System.out.println("");
	    }
	}

    }//GEN-LAST:event_chargerMapActionPerformed
	private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = false;
	    texture = Textures.HERBECENTRE;
	}//GEN-LAST:event_jRadioButton5ActionPerformed

	private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUFONDBAS;
	}//GEN-LAST:event_jRadioButton6ActionPerformed

	private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDUREEAUBAS;
	}//GEN-LAST:event_jRadioButton7ActionPerformed

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUDROIT;
	}//GEN-LAST:event_jRadioButton1ActionPerformed

	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUGAUCHE;
	}//GEN-LAST:event_jRadioButton2ActionPerformed

	private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUHAUT;
	}//GEN-LAST:event_jRadioButton3ActionPerformed

	private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUHAUTGAUCHE;
	}//GEN-LAST:event_jRadioButton4ActionPerformed

	private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDUREEAUDROIT;
	}//GEN-LAST:event_jRadioButton8ActionPerformed

	private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDUREEAUGAUCHE;
	}//GEN-LAST:event_jRadioButton9ActionPerformed

	private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUFONDDROIT;
	}//GEN-LAST:event_jRadioButton10ActionPerformed

	private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUVIRAGEBASDROIT;
	}//GEN-LAST:event_jRadioButton11ActionPerformed

	private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUVIRAGEHAUTDROIT;
	}//GEN-LAST:event_jRadioButton12ActionPerformed

	private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUFONDGAUCHE;
	}//GEN-LAST:event_jRadioButton13ActionPerformed

	private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUVIRAGEHAUTGAUCHE;
	}//GEN-LAST:event_jRadioButton14ActionPerformed

	private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUVIRAGEBASGAUCHE;
	}//GEN-LAST:event_jRadioButton15ActionPerformed

	private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAU;
	}//GEN-LAST:event_jRadioButton16ActionPerformed

	private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.EAUHAUTDROIT;
	}//GEN-LAST:event_jRadioButton17ActionPerformed

	private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.MONTAGNEHAUTDROIT;
	}//GEN-LAST:event_jRadioButton24ActionPerformed

	private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.MONTAGNEHAUTGAUCHE;
	}//GEN-LAST:event_jRadioButton18ActionPerformed

	private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.MONTAGNEHAUT;
	}//GEN-LAST:event_jRadioButton23ActionPerformed

	private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.MONTAGNECENTREGAUCHE;
	}//GEN-LAST:event_jRadioButton21ActionPerformed

	private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.MONTAGNECENTRE;

	}//GEN-LAST:event_jRadioButton20ActionPerformed

	private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.MONTAGNECENTREDROIT;

	}//GEN-LAST:event_jRadioButton25ActionPerformed

	private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;
	    texture = Textures.MONTAGNEBASDROIT;

	}//GEN-LAST:event_jRadioButton22ActionPerformed

	private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;

	    texture = Textures.MONTAGNEBAS;

	}//GEN-LAST:event_jRadioButton19ActionPerformed

	private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
	    obstacle = true;
	    suppression = false;
	    bordure = false;

	    texture = Textures.MONTAGNEBASGAUCHE;
	}//GEN-LAST:event_jRadioButton26ActionPerformed

	private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
	    suppression = true;
	    obstacle = false;
	    bordure = false;
	}//GEN-LAST:event_jRadioButton27ActionPerformed

	private void jRadioButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton32ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = false;
	    texture = Textures.SABLECENTRE;
	}//GEN-LAST:event_jRadioButton32ActionPerformed

	private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLEHAUTGAUCHE;
	}//GEN-LAST:event_jRadioButton28ActionPerformed

	private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLEHAUT;
	}//GEN-LAST:event_jRadioButton29ActionPerformed

	private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLEHAUTDROIT;
	}//GEN-LAST:event_jRadioButton30ActionPerformed

	private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLEGAUCHE;
	}//GEN-LAST:event_jRadioButton31ActionPerformed

	private void jRadioButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton33ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLEDROIT;
	}//GEN-LAST:event_jRadioButton33ActionPerformed

	private void jRadioButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton34ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLEBASGAUCHE;
	}//GEN-LAST:event_jRadioButton34ActionPerformed

	private void jRadioButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton36ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLEBASDROIT;
	}//GEN-LAST:event_jRadioButton36ActionPerformed

	private void jRadioButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton35ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLEBAS;
	}//GEN-LAST:event_jRadioButton35ActionPerformed

	private void jRadioButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton37ActionPerformed
	    obstacle = false;
	    suppression = false;
	    bordure = true;
	    texture = Textures.BORDURESABLECOINBASDROIT;
	}//GEN-LAST:event_jRadioButton37ActionPerformed

    private void creerMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerMapActionPerformed
	for (int i = 0; i < aireDeJeu1.getPlateau().getNbLigne(); i++) {
	    for (int j = 0; j < aireDeJeu1.getPlateau().getNbColonne(); j++) {
		aireDeJeu1.getPlateau().get(i, j).setBordure(null);
		aireDeJeu1.getPlateau().get(i, j).setObstacle(null);
		aireDeJeu1.getPlateau().get(i, j).setTypeTerrain(Textures.ROC);
	    }
	}
	aireDeJeu1.repaint();
    }//GEN-LAST:event_creerMapActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ihm.AireDeJeu aireDeJeu1;
    public editeur.AireDeSelection aireDeSelection1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem chargerMap;
    private javax.swing.JMenuItem creerMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JMenuItem sauverMap;
    // End of variables declaration//GEN-END:variables

    public AireDeJeu getAireDeJeu1() {
	return aireDeJeu1;
    }
}
